insert into raza (nombre, esperanzaVida, tamanho) values ('Afgano', 14 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Akita', 10 , 'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Basenji', 8 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Basset Hound', 12,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Basset Griffon', 21,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Beagle',23 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Bedlington Terrier',12 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Bichón Frisé', 11,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Bloodhound', 11, 'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Bobtail',12 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Border Collie',12,'Mediano');
insert into raza (nombre, esperanzaVida, tamanho) values ('Boston Terrier',12 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Bóxer',14 ,'Mediano');
insert into raza (nombre, esperanzaVida, tamanho) values ('Boyero de Berna', 12,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Braco de Weimar',15 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Bull Terrier',20 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Bulldog Frances', 10,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Bulldog Ingles',11 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Caniche', 11,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Caniche Grande', 12,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Carlino',13 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Cavalier King Charles Spaniel', 14,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Chihuahua', 15,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Chow Chow',15 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Cocker Spaniel Ingles',16 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Corgi Gales de Pembroke',17 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Crestado Chino', 18,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Dalmata', 12,'Mediano');
insert into raza (nombre, esperanzaVida, tamanho) values ('Doberman', 11,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Dogo de Burdeos',13 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Fox Terrier', 16,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Galgo', 10,'Mediano');
insert into raza (nombre, esperanzaVida, tamanho) values ('Golden Retriever',9 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Gran Danes',8 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Grifon de Bruselas',16 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Husky Siberiano', 12,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Jack Russell Terrier', 11,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Kerry Blue Terrier', 13,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Komondor',18 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Labrador Retriever', 17,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Lhasa Apso', 12,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Maltes', 14,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Mastin Ingles',16 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Mastin Napolitano',15 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Mastin Tibetano', 19,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Papillon', 12,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Pastor Aleman', 11,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Pastor Australiano',13 ,'Mediano');
insert into raza (nombre, esperanzaVida, tamanho) values ('Pastor Belga', 13,'Mediano');
insert into raza (nombre, esperanzaVida, tamanho) values ('Pastor de Shetland',12 ,'Mediano');
insert into raza (nombre, esperanzaVida, tamanho) values ('Perro de Agua Portugues',11 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Perro del Faraon',17 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Pinscher Aleman', 16,'Mediano');
insert into raza (nombre, esperanzaVida, tamanho) values ('Pinscher Aleman Enano',12 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Podenco Ibicenco',13 ,'Mediano');
insert into raza (nombre, esperanzaVida, tamanho) values ('Pointer',16 ,'Mediano');
insert into raza (nombre, esperanzaVida, tamanho) values ('Pomerania',17 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Puli',15 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Rottweiler',13 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Samoyedo',11 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('San Bernardo', 12,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Schnauzer',14 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Setter Irlandes',14 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Shar Pei',17 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Shiba Inu',13 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Shih Tzu',12 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Spitz Aleman', 11,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Teckel',12 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Terranova',18 ,'Grande');
insert into raza (nombre, esperanzaVida, tamanho) values ('Terrier Australiano',17 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Terrier de Airedale',18 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Terrier Escoces', 14,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Terrier Irlandes',15 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Terrier Tibetano',13 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('West Highland White Terrier',12 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Xoloitzcuintle',12 ,'Pequeno');
insert into raza (nombre, esperanzaVida, tamanho) values ('Yorkshire Terrier', 11,'Pequeno');